### ISSUE TITLE
How to use pa11y task?

### ISSUE THREAD

**Issue by jonraedeke** [acquia-pso/cog#150]
I'm confused about how to use the `gulp test:pa11y` task. I assumed I could use this test locally by adding my local url to the pa11y urls setting in gulpfile.js, but I get the following error when I do that.

`The page option must only be set alongside the browser option`

**Comment by sarahjean** [comment]
@jonraedeke I think I know what happened here, the package.json was only specifying the version as 'beta', and `npm install` by itself doesn't always respect the lockfile. So the settings in the gulpfile are for beta 8. so if you do `npm install --save-dev  pa11y@5.0.0-beta.8` that will get it working with the current settings. That said, we should update the starterkit so that it can use the newer version and make some config changes for beta 10 (the version I am guessing you have now).

**Comment by jonraedeke** [comment]
@sarahjean Thanks for the quick reply. That gets me farther, but I get a timeout. I'll keep trying. Thanks for all your work on this. I'm excited to try this out.

```Launching Headless Chrome
Opening URL in Headless Chrome
Setting request method
Setting request headers
[15:49:12] Pa11y timed out (30000ms)```

**Comment by aellison** [comment]
@jonraedeke If you don't need to run accessibility tests regularly in a CI environment, you may want to look into https://github.com/pa11y/pa11y-dashboard. It's a more robust and easy to use testing tool than this gulp task.

**Comment by jonraedeke** [comment]
@aellison Thanks for that. The dashboard does look more useful. If I have time to update the gulp task, I'll report back. For now, closing this.
