### ISSUE TITLE
Gulp-cli

### ISSUE THREAD

**Issue by vbouchet31** [acquia-pso/cog#73]
I followed all the steps described in [Setup Local Development](https://github.com/acquia-pso/cog/blob/8.x-1.x/STARTERKIT/README.md#setup-local-development) and everything worked fine until the `gulp watch` command.

`$ gulp watch
-bash: gulp: command not found
`

After a quick google search, it seems I missed the glup-cli "tool". I ran `$ sudo npm install -g gulp-cli` and after that everything worked as expected.

Not sure it is expected, if it should be documented or if I did something wrong.
OSX El Capitan 11.11.6

**Comment by sarahjean** [comment]
@vbouchet31 Yes that's expected, you need to install a global gulp to run gulp. It does look like that could be explicitly stated on https://github.com/acquia-pso/cog/blob/8.x-1.x/STARTERKIT/README.md

Also on the full setup it is listed at the very bottom: https://github.com/acquia-pso/cog/blob/8.x-1.x/STARTERKIT/_readme/setup-full.md but it gives 'gulp' instead of 'gulp-cli'.

So yeah this could be a docs improvement.

**Comment by jenter** [comment]
@vbouchet31 this was resolved by PR https://github.com/acquia-pso/cog/pull/83
